services:
  backend:
    build:
      context: ./backend
    container_name: invest-immo-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: invest-immo-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    restart: unless-stopped